---
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: junit:junit:4.13.1 org.leplus:ristretto:1.0.0
    environment:
      - ONLINE_KEYS=6B1B9BE54C155617,85911F425EC61B51
